In [1]:
import pandas
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline
import numpy as np

In [2]:
f = open('statistics.csv')
dataFrame_in = pandas.read_csv(f)
pandas.options.display.float_format = '{:,.0f}'.format
dataFrame_in

Winning  Time  Score        Algo
0     False    42   1060     MINIMAX
1     False   127   1810     MINIMAX
2     False   135   2280     MINIMAX
3     False   124   2190     MINIMAX
4     False   142   3150     MINIMAX
5     False   174   2850     MINIMAX
6     False   169   3520     MINIMAX
7     False   188   3870     MINIMAX
8     False   143   2650     MINIMAX
9     False   123   3230     MINIMAX
10    False    91   3080     MINIMAX
11    False   163   2860     MINIMAX
12    False    74   1490     MINIMAX
13    False   168   2460     MINIMAX
14    False    74    960     MINIMAX
15    False   236   2860     MINIMAX
16    False   134   1720     MINIMAX
17    False   194   3440     MINIMAX
18    False    69   1430     MINIMAX
19    False   114  81190     MINIMAX
20    False    71   1210     MINIMAX
21    False   114   1480     MINIMAX
22    False   118   3700     MINIMAX
23    False    93   1810     MINIMAX
24    False   149   2540     MINIMAX
25    False   114   1440     MINIMAX
26    False    45   1080     MINIMAX
27    False    89    940     MINIMAX
28    False    90   1500     MINIMAX
29    False   155   3690     MINIMAX
30    False   132   2750     MINIMAX
31    False   143   2250     MINIMAX
32    False    86   3220     MINIMAX
33    False    96   1860     MINIMAX
34    False    53    750  EXPECTIMAX
35    False     5    100  EXPECTIMAX
36    False    72   1630  EXPECTIMAX
37    False   159   3110  EXPECTIMAX
38    False   231   3200  EXPECTIMAX
39    False     4     70  EXPECTIMAX
40     True   171   4320  EXPECTIMAX
41    False    56   5110  EXPECTIMAX
42    False   126   2130  EXPECTIMAX
43    False   113   2370  EXPECTIMAX
44    False    74   1470  EXPECTIMAX
45    False   200   3500  EXPECTIMAX
46    False     7    130  EXPECTIMAX
47    False   100   1000  EXPECTIMAX
48    False   105   1970  EXPECTIMAX
49    False   201   3380  EXPECTIMAX
50    False    73   1420  EXPECTIMAX
51    False   140   2380  EXPECTIMAX
52    False   204   4150  EXPECTIMAX
53    False   202   3580  EXPECTIMAX
54     True   234   4520  EXPECTIMAX
55    False     5   4550  EXPECTIMAX
56     True   224   4380  EXPECTIMAX
57    False   173   8440  EXPECTIMAX

In [3]:
dataFrame = dataFrame_in.copy()
algoList = dataFrame['Algo'].tolist()
WinningList = dataFrame['Winning'].tolist()

In [4]:
labelEncoderAlgo = LabelEncoder()
labelEncoderAlgo.fit(algoList)
labelsAlgo= labelEncoderAlgo.transform(algoList)
dataFrame['Algo']=pandas.Series(labelsAlgo)
labelEncoderWin = LabelEncoder()
labelEncoderWin.fit(WinningList)
labelsWin= labelEncoderWin.transform(WinningList)
dataFrame['Winning']=pandas.Series(labelsWin)
dataFrame

Winning  Time  Score  Algo
0         0    42   1060     1
1         0   127   1810     1
2         0   135   2280     1
3         0   124   2190     1
4         0   142   3150     1
5         0   174   2850     1
6         0   169   3520     1
7         0   188   3870     1
8         0   143   2650     1
9         0   123   3230     1
10        0    91   3080     1
11        0   163   2860     1
12        0    74   1490     1
13        0   168   2460     1
14        0    74    960     1
15        0   236   2860     1
16        0   134   1720     1
17        0   194   3440     1
18        0    69   1430     1
19        0   114  81190     1
20        0    71   1210     1
21        0   114   1480     1
22        0   118   3700     1
23        0    93   1810     1
24        0   149   2540     1
25        0   114   1440     1
26        0    45   1080     1
27        0    89    940     1
28        0    90   1500     1
29        0   155   3690     1
30        0   132   2750     1
31        0   143   2250     1
32        0    86   3220     1
33        0    96   1860     1
34        0    53    750     0
35        0     5    100     0
36        0    72   1630     0
37        0   159   3110     0
38        0   231   3200     0
39        0     4     70     0
40        1   171   4320     0
41        0    56   5110     0
42        0   126   2130     0
43        0   113   2370     0
44        0    74   1470     0
45        0   200   3500     0
46        0     7    130     0
47        0   100   1000     0
48        0   105   1970     0
49        0   201   3380     0
50        0    73   1420     0
51        0   140   2380     0
52        0   204   4150     0
53        0   202   3580     0
54        1   234   4520     0
55        0     5   4550     0
56        1   224   4380     0
57        0   173   8440     0

In [5]:
normalized_df=(dataFrame-dataFrame.min())/(dataFrame.max()-dataFrame.min())
normalized_df

Winning  Time  Score  Algo
0         0     0      0     1
1         0     1      0     1
2         0     1      0     1
3         0     1      0     1
4         0     1      0     1
5         0     1      0     1
6         0     1      0     1
7         0     1      0     1
8         0     1      0     1
9         0     1      0     1
10        0     0      0     1
11        0     1      0     1
12        0     0      0     1
13        0     1      0     1
14        0     0      0     1
15        0     1      0     1
16        0     1      0     1
17        0     1      0     1
18        0     0      0     1
19        0     0      1     1
20        0     0      0     1
21        0     0      0     1
22        0     0      0     1
23        0     0      0     1
24        0     1      0     1
25        0     0      0     1
26        0     0      0     1
27        0     0      0     1
28        0     0      0     1
29        0     1      0     1
30        0     1      0     1
31        0     1      0     1
32        0     0      0     1
33        0     0      0     1
34        0     0      0     0
35        0     0      0     0
36        0     0      0     0
37        0     1      0     0
38        0     1      0     0
39        0     0      0     0
40        1     1      0     0
41        0     0      0     0
42        0     1      0     0
43        0     0      0     0
44        0     0      0     0
45        0     1      0     0
46        0     0      0     0
47        0     0      0     0
48        0     0      0     0
49        0     1      0     0
50        0     0      0     0
51        0     1      0     0
52        0     1      0     0
53        0     1      0     0
54        1     1      0     0
55        0     0      0     0
56        1     1      0     0
57        0     1      0     0

In [6]:
indexes = np.array(normalized_df.index.values).reshape(-1, 1)
to_predict_indexes= list(range(len(indexes), len(indexes)+5))
to_predict_indexes= np.array(to_predict_indexes).reshape(-1, 1)
score = np.array(normalized_df['Score']).reshape(-1, 1)

In [7]:
regsr=make_pipeline(PolynomialFeatures(),LinearRegression())
regsr.fit(indexes, score)

Pipeline(steps=[('polynomialfeatures', PolynomialFeatures()),
                ('linearregression', LinearRegression())])

In [8]:
predicted_score = regsr.predict(to_predict_indexes).reshape(-1, 1)
predicted_score

array([[0.02444975],
       [0.02277585],
       [0.0210565 ],
       [0.01929169],
       [0.01748141]])

In [9]:
regsr.fit( np.array(normalized_df['Score']).reshape(-1, 1),  np.array(normalized_df['Time']).reshape(-1, 1))
predicted_time = regsr.predict(predicted_score)
predicted_time

array([[0.4624622 ],
       [0.44714318],
       [0.43135354],
       [0.41508891],
       [0.39834478]])

In [10]:
regsr = LogisticRegression()
regsr.fit( np.array(normalized_df['Score']).reshape(-1, 1) ,  np.array(normalized_df['Winning']))
predicted_winning = regsr.predict(predicted_score)
predicted_winning

array([0., 0., 0., 0., 0.])

In [11]:
regsr.fit( np.array(normalized_df['Score']).reshape(-1, 1) ,  np.array(normalized_df['Algo']))
predicted_algo = regsr.predict(predicted_score)
predicted_algo

array([1., 1., 1., 1., 1.])

In [12]:
new_predicted_time =[]
new_predicted_score = []
for i in range(len(predicted_time)):
    new_predicted_time.append(predicted_time[i][0])
for i in range(len(predicted_score)):
    new_predicted_score.append(predicted_score[i][0])
new_predicted_winning = []
new_predicted_algo = []
for index in range(5):
    if(list(predicted_winning)[index] == 0):
        new_predicted_winning.append(False)
    else:
        new_predicted_winning.append(True)
    if(list(predicted_algo)[index] == 0):
        new_predicted_algo.append("EXPECTIMAX")
    else:
        new_predicted_algo.append("MINIMAX")

In [13]:
dict = {'Winning':new_predicted_winning, 'Time':new_predicted_time, 'Score':new_predicted_score, 'Algo':new_predicted_algo}
result = pandas.DataFrame(dict)
result

Winning  Time  Score     Algo
0    False     0      0  MINIMAX
1    False     0      0  MINIMAX
2    False     0      0  MINIMAX
3    False     0      0  MINIMAX
4    False     0      0  MINIMAX

In [14]:
result_df = result.copy()
result_df['Score'] = round((result_df['Score']*(dataFrame['Score'].max()-dataFrame['Score'].min()) + dataFrame['Score'].min()),0)
result_df['Time'] = (result_df['Time']*(dataFrame['Time'].max()-dataFrame['Time'].min()) + dataFrame['Time'].min())
result_df

Winning  Time  Score     Algo
0    False   111  2,053  MINIMAX
1    False   108  1,918  MINIMAX
2    False   104  1,778  MINIMAX
3    False   100  1,635  MINIMAX
4    False    96  1,488  MINIMAX

In [15]:
dataFrame_in = dataFrame_in.append(result_df, ignore_index=True)
dataFrame_in.to_csv('out.csv', index=False) 
dataFrame_in

Winning  Time  Score     Algo
0     False    42  1,060  MINIMAX
1     False   127  1,810  MINIMAX
2     False   135  2,280  MINIMAX
3     False   124  2,190  MINIMAX
4     False   142  3,150  MINIMAX
..      ...   ...    ...      ...
58    False   111  2,053  MINIMAX
59    False   108  1,918  MINIMAX
60    False   104  1,778  MINIMAX
61    False   100  1,635  MINIMAX
62    False    96  1,488  MINIMAX

[63 rows x 4 columns]